[tool.ruff]
select = [
    "F", "E", "W", "I", "N",
    "UP",
    "B", "COM", "C4", "Q", "RSE", "RET", "SIM", "TCH", "ARG", "PTH",
    "PLE", "PLR", "PLW", "NPY", "RUF"
]
ignore = ["B905"]
show-fixes = true

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"